import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Page from "./Navbar/Page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body className="bg-black text-white">
        <div className="flex h-screen m-4">
          <div className="w-[20%]">
            <Page/>
          </div>
          <div className="w-[80%] overflow-y-auto scrollbar-hide">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
